services:
  animal_registry:
    build:
      context: ./AnimalRegistryODataApi/
      dockerfile: Dockerfile
    container_name: animal_registry
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/AnimalRegistryODataApi.pfx
      - ConnectionStrings__DefaultConnection=Data Source=oracle:1521/XE;User Id=system;Password=pas5w0rd!;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - oracle

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_PWD=pas5w0rd!
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: